DBUSER = 'assetnote'
DBPASS = 'CHANGE_ME_TOO'
DBHOST = '127.0.0.1'
DBPORT = '3306'
DBNAME = 'assetnote'
SECRET_KEY = 'CHANGEME'
PUSHNOTIFY_KEY = ''
debug=True

SQLALCHEMY_DATABASE_URI = 'mysql://{0}:{1}@{2}:{3}/{4}'.format(DBUSER, DBPASS, DBHOST, DBPORT, DBNAME)
SQLALCHEMY_TRACK_MODIFICATIONS = False
SECURITY_TRACKABLE = True
SECURITY_CHANGEABLE = True
SECURITY_PASSWORD_HASH = 'bcrypt'
SECURITY_PASSWORD_SALT = 'CHANGEME'
SECURITY_DEFAULT_REMEMBER_ME = False
SECURITY_LOGIN_USER_TEMPLATE = 'security/login_user.html'
SECURITY_CHANGE_PASSWORD_TEMPLATE = 'security/change_password.html'
