import os

DBUSER = 'assetnote'
ROOT_DBPASSWD = "CHANGE_ME_DAMNIT"
DBPASS = 'CHANGE_ME_TOO'
SECRET_KEY = 'CHANGEME'
PUSHNOTIFY_KEY = ''

if 'DBHOST' in os.environ:
    # Vagrant
    DBHOST = os.environ['DBHOST']
else:
    # Docker
    DBHOST = 'database'

DBPORT = '3306'
DBNAME = 'assetnote_db'
debug=False

SQLALCHEMY_DATABASE_URI = 'mysql://{0}:{1}@{2}:{3}/{4}'.format(DBUSER, DBPASS, DBHOST, DBPORT, DBNAME)
SQLALCHEMY_TRACK_MODIFICATIONS = False
SECURITY_TRACKABLE = True
SECURITY_CHANGEABLE = True
SECURITY_PASSWORD_HASH = 'bcrypt'
SECURITY_PASSWORD_SALT = 'CHANGEME'
SECURITY_DEFAULT_REMEMBER_ME = False
SECURITY_LOGIN_USER_TEMPLATE = 'security/login_user.html'
SECURITY_CHANGE_PASSWORD_TEMPLATE = 'security/change_password.html'
